### PR TITLE
cleanup no longer used update site in the root of the repo

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
Eclipse Marketplace already references the new location in updatesite/nightly

**Comment by apupier** [comment]
which update site is used by Jboss Tools?

**Comment by lhein** [comment]
Uhm good questionAm 18.06.2018 17:32 schrieb Aurélien Pupier <notifications@github.com>:which update site is used by Jboss Tools?

**Comment by nickboldt** [comment]
I use https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/archive/master.zip --> mirrored to a folder under http://download.jboss.org/jbosstools/updates/requirements/camel-lsp-client/ such as http://download.jboss.org/jbosstools/updates/requirements/camel-lsp-client/1.0.0.201806081234

**Comment by nickboldt** [comment]
See also https://github.com/camel-tooling/camel-lsp-client-eclipse/pull/37 for another approach to deployment.

**Review by apupier — CHANGES_REQUESTED** [review]
> I use https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/archive/master.zip --> mirrored to a folder under http://download.jboss.org/jbosstools/updates/requirements/camel-lsp-client/ such as http://download.jboss.org/jbosstools/updates/requirements/camel-lsp-client/1.0.0.201806081234

ok then this PR will break the workflow.

**Comment by nickboldt** [comment]
> ok then this PR will break the workflow.

Sure but I can update my workflow when pulling new master update site zips into the JBT TP. So that's not a problem. We're allowed to evolve :D 

copying the zip and unpacking is arguably easier, but if you're now publishing only an unzipped site, I can still mirror from that site. It's just an extra, slower step to use p2.mirror rather than just 'get the zip and unpack it'.

**Comment by nickboldt** [comment]
Would it be possible to publish a zip into https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/tree/master/updatesite eg., https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/tree/master/updatesite/repository.zip ?

**Comment by lhein** [comment]
The current way of populating this update site is as follows...

SNAPSHOTS go into 
https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/tree/master/updatesite/nightly

RELEASES go into
https://github.com/camel-tooling/camel-lsp-client-eclipse-update-site/tree/master/updatesite/stable

@nickboldt 
You should adapt your script that pulls the update site to consider this.

**Comment by nickboldt** [comment]
Stable site is empty / 404'd.

Will you have a process in place to populate this site soon? Do you need me to pull newer camel-lsp-client features? I pull them when I think of it or when someone asks, but there's zero automated interlink between this project and the jbosstools target platform site. It would be way better if this project was publishing the same way that jbosstools-server or jbosstools-fuse was.

**Comment by lhein** [comment]
We have not released a GA version yet. So it's normal that stable site is 404 atm.

**Pull request closed without merging**
